Stop ricing and be a silent observer for awhile

diff --git a/local/.local/bin/urxvt_daemon b/local/.local/bin/urxvt_daemon
--- a/local/.local/bin/urxvt_daemon
+++ b/local/.local/bin/urxvt_daemon
@@ -1,6 +1,7 @@
 #!/bin/sh
-
-if ! urxvtc "$@"
-  urxvtd -q -o -f
-  urxvtc "$@"
+if ! urxvtc "$@" ; then
+ echo "failed to start ($?), trying to start daemon"
+ urxvtd &
+ sleep 1
+ exec urxvtc "$@"
 fi
